# Exploring Impresso Tools (NER, NEL, article embeddings)

This notebook provides an overview and demonstration of the core tools integrated into the Impresso application, focusing on components that power text understanding, entity recognition, and retrieval capabilities across the corpus. 

This notebook documents production-level tools that are permanent within the Impresso infrastructure.

Specifically, we cover three major components:

* **Named Entity Recognition (NER)** – identifying and classifying named entities (e.g., people, places, organizations) in historical newspaper text using the [impresso-project/ner-stacked-bert-multilingual](https://huggingface.co/impresso-project/ner-stacked-bert-multilingual) model.
* **Named Entity Linking (NEL)** – resolving recognized entities to canonical entries in knowledge bases such as Wikidata, using the [impresso-project/nel-mgenre-multilingual](https://huggingface.co/impresso-project/nel-mgenre-multilingual) model.
* **Article Embeddings** – generating embeddings of full articles using [gte-multilingual-base](https://huggingface.co/Alibaba-NLP/gte-multilingual-base) to enable semantic search with:
    - **In-corpus queries** – selecting a query directly from the *Impresso* corpus.  
    - **Out-of-corpus queries** – embedding an external query (e.g., manually formulated or from another source).

In [ ]:
from impresso import connect

impresso = connect()

### Named entity recognition

In [2]:
text = """
    Jean-Baptiste Nicolas Robert Schuman ( 
    29 June 1886 – 4 September 1963) was a Luxembourg-born French 
    statesman. Schuman was a Christian democratic (Popular 
    Republican Movement) political thinker and activist. 
    """
result = impresso.tools.ner(
    text=text
)
result

### Named entity linking

For the system to know what entity to link, we need to surround it with the markers [START] and [END]. Leave spaces between the entity and the markers.

In [3]:
text = """
    [START] Jean-Baptiste Nicolas Robert Schuman [END] ( 
    29 June 1886 – 4 September 1963) was a Luxembourg-born French 
    statesman. Schuman was a Christian democratic (Popular 
    Republican Movement) political thinker and activist. 
    """

result = impresso.tools.nel(
    text=text,
)
result

### Named entity recognition and linking

This method will do entity recognition and linking at the same time.

In [4]:
text = """
    Jean-Baptiste Nicolas Robert Schuman ( 
    29 June 1886 – 4 September 1963) was a Luxembourg-born French 
    statesman. Schuman was a Christian democratic (Popular 
    Republican Movement) political thinker and activist. 
    """
result = impresso.tools.ner_nel(
    text=text,
)
result

### Article embeddings

All content items in the Impresso data of type _article_ longer than 800 characters were embedded using [gte-multilingual-base](https://huggingface.co/Alibaba-NLP/gte-multilingual-base) which is the latest in the GTE (General Text Embedding) family that has a strong multilingual capability.

In [5]:
text = """
    Jean-Baptiste Nicolas Robert Schuman ( 
    29 June 1886 – 4 September 1963) was a Luxembourg-born French 
    statesman. Schuman was a Christian democratic (Popular 
    Republican Movement) political thinker and activist. 
    """

text_space_embedding = impresso.tools.embed_text(text=text, target="text")
text_space_embedding

'gte-768:Fao1vWPioj3Msv+7LwqfPLicTb2kPgO+pkpAPVhbkL1cdi891oY9vYv1dDzSHTC9dJ0MvYGTZT3d87C90kt6PZ81gT0pg4c7x6XRPdfOC70xllU9WJrxO/pBwDwDI1C8YveXvZ3gyrzDjek9FkkhvXFAoL2LjYo9W0XwvKLdFLsg10C7QGhjPcAUHD1Z4YC8yFZhPbxhnToLYza9cFl8vMkdYTw0DZG8Mr10vX8zIjo/ZTs8AYC1PGyAn70CFaS7PAyNvNqxPT0AUyC9eiAyPXVJo7y1OGM9r/8TPdFwez1HIaS9lXUHvGb4Aj4N9oK9wTlNvQBmOrtQG9E7WqmPvUjIYLx6jZa8hOEFPV6vkLzIEoM9latiPej5i7s72xI8NmLBurlZuDzdEyw8gD7mPcUoQLytEUk6CfLAPfnsOD1UKy29vVunvBrRozzb8jU9op9OPJnZqTyJeE+8bchbvT3uhLxL2WU9toKuPfffBrwuxZk8H2PLvG6TWby+ei09OKuLvAUJTL0mvh08oOuDvYTpiTsBNQ47CNTAPB3frbzvPi88CUQ9vcza/LwKvRs91lUCPPlTCjx/bH+9dEkovK43K70N5bC8+BMxvcgJBz1vxoo9JQygvHvAkz3VDry8nWWzuwuSJ72RL+a8lJP5vJPTur1O3uG8Ph27vGo/LL0q7ew8mvK9vBMQmD3kaIU93Lg1PejcIb1ffAg9y4wuvDBo2LxlEzc9SWfWunvsKb228fy8F7iKPBLTSL2OFiO9T4+JPOr5jzuas5K8grgMuy6EQzzGCF69W2DZPKX7JT3C/908EIxYvaKCMrwC3e28KIJJvLBgGj0P+Im8LMJuvGClrT2C4W67DOx6u/g0rbummEI8UquLPKSzvrwj1nk8OyIoPXR3ILxpzxy98WElPW2ejDxP2jK8vsGBvKCdBD1QD/K8sieVPc6Cjr0mm6k7U8SCvEEc9LyS4Iq9STFGvGc7uLsB0bg8kPsMvf71OL1OeyE8xRFePMzPlLwlezA8mk6FvZepnTygYVm8lpG/vSrQE70AAZo9dW9tvKEhMDw3tzM9JxoBPQQrfz1oTuA8PLAyPTZcT7zgAJ27is46vJwGMrzvySK9aSHsPKMgBzx3DUU8LM9OPSKZLr2bfkC8NAxEvUJnyrwaLyk8kDEHvdzT8by4SLe8ihZfvc4Bn71960I92S0sPYRbJTpyUBw9kjFBPM6NsjyVPf+8xJrePDDPbrxxoXm9TomuOp9iw7vczX28Cwy5vNWlFrxusiE95cLcPKQBdrzeF/A8oUoNPCiY5LySdkO9exmBPEWYAbu0dzg8ZbvUOuFCHL25xvk8CGmPvPW+ELwGwC89tsSCPNrVND1qxde8wMZBPdphLDtXLgO9ltB3O0HdljvoDCS76XEvPWikL730pcU8rzN6PEWfEL0nL4U8RkJSuz9WGT1B9Vc6bO4aO8ZaNr0bEbw8kx6ovSSNdbz79707pqSJOz+2Nz26XpE8rrukvC6WvzkEPiy9haWUPSanjDw7xIo7iyCLO3pH57v+h3Q7AYOiu6m7r7zROxW75Dm+PJsavb3b49S9xarFuxI6mTsIBE+860WOPCQhuLuGPg49SIv8PF0f7Trvn4y8A+xZvYJWlLzP/XG6VdBdvVypPjkCnrm85P5/PO3zS73+Adg6S7cTvJEkk7zksFQ9WJANvR9u9LzuLDS9/6lOPbK26bxHOCc9Jhe9vOutYrxDnWu6fV7zOjkbGL1G4d28M76NPO6FgTy6dXA8bidnvcTxqDzBSjS9/ykjPMqsRjvicHM8/dRsO4ODubw6nQM9Aa3JvYEvYD1Lqq+8zqH3vPIaMjxxD868qD45vCfHFzqe84S6bNcWPeMPvDtdVJE9NUAlvEWahTw8OMW7l9UePTSgeb1fym09T8ZAPenUuLz8wZU92C8GPMWIoj0D2Y+8X82HvUBCuDwwSJW8g9PlO66ndjzMbi89yL8UvNg2Xj1ahaa8CPdmO6NkFD3si2s9/MGdPODKHb3wY5k7dq54Pagplj32DUk8nZsdPLiM/7yMrMo8DXxQPUKaWj2G+oG8ARQXu59o07yzynE8jSu2PN1QUzt14Ju8baxvPKdDzzzvh968hA5EPRlkIT3s/Lw8qi6iPMu7wDz1Tmm9AJRJPN6sPD0ysUe8qOWBOgnuf7wy7Ss9wXNUva8HoD1WWKu8A02wvDoVYj25MK26lVSEPPRYEz7054m88q3Wu+/HyDwdstU8fPgmvUca97zGigI7HH4JPRhFKD1RtSO97Z0hPSUjmr3L3wI9XarYPG18CL3+1wi985qOO1XFBTxMC4y8RFryPH62ID1Foh48L2qGOjWQtzyzxou9/8IPPBpMPTxwqXc9AI6LPas9U7yD9jS9bgpQvSYFML1F6DS847GHPM/Z4zwxSyq82X5/usUL4DzAyo48HReVvN7ZfbwE7pS8smoxPfbUBr1njLA86H4wPbXUirukqWk9x9tROh8TWbx4QDm9eshOPEXhprx+oBK9EJkHPVYNAD2rYFm90V6BvENfjjwiI4m4O+1aPC7oQzwed2s856AhvKBkE7008Dk8cUTaOxr6rr21I408yucmPf5ixbzQmN08B0VhPHgWn7zW0Bc9Tp8PPWcNWTwrzsa7sYUsPO0hKbyrSwW9AVRRvTVcFbwpevs8nPqHveffgrwJ/3Y9jsVnPcSSUzzpLT+9UuoxvXH2jDyVhxg9JDGEvXIWIb1+EEo8IDXXO7z7Jb3Sb1q8hlUsveisQz16Ex69Wy71vJYkLD0Skb88QswPu4B8xTwNQZa8Y3WTu0gAYDxHedo6JFIPPVoQgDssKZg7slNMvAi6ij3EoSY975P5u6pe/DvrIcw8yK+BuzGHhDxnldS7SnwJvM914zx4WQo80+KRPXi5lb1TdO6862kdvJnqUDwEGKC8VSQTPVvIED3RpbS6K2LLu5Lkxzy42ke7NJe+vNAeeT3oAla4apEDvflT7jySHUK8XkD9vGnjyLwF/ze9wwQgveJbbTwQqIE8KQCLPafGVDy7why9PYh6u5F3GbxKID29MTKLvP0oSD0pj9W84Uwou8UW4bxTfWu9dodZvTFvS73kC/a8dlGkPNkkQb3gpIY8zPqZO+iI1jtHxvY6XTg7PRXa/bxGlt67WI4EPewo/7o9bQu8lA5yPIfSbDyl5eI7fvPvPH4kObxE7AU94mALvR2mjjyRb5m7jTgLu2XBjr2975m7jd8KPeNqbL2aPwS7YZ9yPBIuJT0SmpI896JOPNBsgby6gIm8xfqmvMTVPD3KjB+9hoxkuxCJGz0fPUM8NThhPcOC6zt+xR29BvuSPL5LqbxVyuK6ymV1O9SvzLwuV4Q8tOQ9PTqIfTxdFi09alKKuwl6XTuQE2i8D3okO49v0bxSfHE6VeFvPdbmFj3UTnK9/YfZPCTYVzzN4AU8m4ndvBYsCj1urWU8ABAKuXfmXb0ppoo8beOtvHhRWr2XiOa89ynYOyML3byIbIk9HHLSPO1MBT1FQBk9DfyfvCqsNb2IWYk8oCUQPbhLL71lLsU8B5IjO1fgOL0ycMK82sYwvZUSMb0UGh69P8pjPaFck7wnxT68lU0zPRrqCz3kkPG65XKdvEXE0jw4pcI8cSIHvFiOcb0l3Ek9VUOkPChwLzynODe8aQiZvDW5J73IfLQ6hWssvFg2XjyDOKu8606sPCB9ojzrkDE82OjXvDW7AT1QVvY8IYFCPEX8ej2G27w7Ru7iOg+vZzwiSQi72enwPDArtjxJbMk8uwbjvE0aVTxpfOW8aH5RvI9N4jxA90w81ykfvJGJTb3jDPk8dWaduxEHJT2tKYo7pRSsPGrOFbvmSyE9Oea/Ox/Gjz3g/oQ98aR6vNpF8bwjhYq9oabBPHp0I711Tl48yUFhvCTTID37KX48sUpEPNDPEL37nWO8b+TLvA5o6rqLJYA9V2uCu1QCgDwAYRU92wJ7PaXYkT2yzWi9PKNjvEUb8zxqDEI8ZVDlPPM2dzyZ46a8+lpOPYGWy7y0FTS9DJShPADtP72T3o+7dCmdPPZ5qDwGSBO9zBAEPOryVrpgZiE9'

#### Search by text embedding with `tools.embed_text` with an out-of-corpus embedding

The `include_embeddings` flag is `False` by default to avoid downloading embeddings for items that may not be needed.

In [6]:
result = impresso.search.find(
  embedding=text_space_embedding,
  limit=5,
  include_embeddings=True,
)

result

Get embeddings by ID.

In [7]:
first_item_embeddings = result.df['semanticEnrichments.embeddings'].iloc[0][0]
first_item_embeddings

'gte-768:pRhKvXXfWz0f+gq9dFx+PZVbvb04PCC9mMWnOj6kQrwie6A8JTVevWjFYbxStA48ECQLvZTBtD2Qece8ramIPSPfTz2Pm8Q6GAS5PTq0q7umh0s9hTmdPRPpmjyLlAK8mz0zvJFJKb2Ra6Y9drPwvdbBnb1stXg9cP1lvVgzXLuFOLk8YzDwPN7XpD3gqXG8XJJ0PeEK0jwSC5g6TGOXPIP51TuAIGq8HGPRu3p0TTxk1co8fjaOu6fJfbyBgUq8LW1iPARMQ7uD+dW7ExdxPbT5m7rYnHQ8jwpGPSW6Azzpnfu9tqpPPRh9KD6/fFy9hIeFvHqhHLtONsi8igZTO1X/SrxB+lC9EF0zPebY67y75Js9468sPd4au7yx8+A8DxuBO67497zAeQ29XzQAPeOCXbyrxOY8LpnNPaY6RzyNe4+924uEPG7/Lb2UR+E8BzxaPK0a9byFcWG7aJeLOycyDzzN+Jo9/9hOPc5xCj197Ng7Ky5/vR7Pgzz+zfw8CH0FvSpwjr337U48AEUBvbiOjbpHS0g9q5YQPa0a9TyA3O+8mnbbvK6/z7yX3ho93JfdvPlZgbxTRKm9nEY9vSUeM73ucxi9JqTfvMuk9zwteDQ93tbAvG+kiLsPfzA97Admu5pqgrxKDQm9zdeBvK1Rsr2nslK8ySCTu6jHkr0JnTo9fxSRPMdFXz04avY8+XqaPUv35Lzcl908KZR2vfJBMr10tFQ9O1kGO+nTVLz0Sjy9ZXqlu/3PRL3i0am8OsvWvN4DED1dyM28VegfvGBAWT1Mvrw7KcFFvDW7Cj2/hy49j5tEvHz3qjxJc4C8xcoEvT9V9jzmzBI6H9gNvTFznT0kFSk7a/eHPVVDRTvGvzI98kEyPMCbCjxOHx08T+d7PWASg7zHtOC8DwVdPNpBzzyYxSe5ml+wvGWoezmwN1s8Twn5PIQ6Ab1ASR06PL01PbHFCr0MsLK9x3u4vDMhgj0SIsO8qs84PKQaEr3Pvg49s1+TPMqYnrxOS4i9C7uEveNUhzt0Lqi8rJ+avS/lbTu7jEU953J0u3knST2FceE6erjHPJppnj1awQs9k8wGvcPPm7y0+Rs7x501vV6EU7x139u72DhFPZXVELwCChE9+vOJu32+AjzJ80O7Y3RqPL72r7yk7UI9Ir8avS14tLzjdgS9U8DnvBgmNr3uc5g8jeoQPfoh4LuD+VU87lEbOwBcrDve1kA8xgMtuzHAIT01CA+9luHpPG/SXjrpvCm8tAX1PItyhTx8n1Q9zy0QuqszaL0ZL0A8ni3Ku+s/B729zIy9Wn2RvDq0qzuvZKo7s41pvTfQ7bwd8QA9PSy3O316iD1jwW49vaz6u83XgTzRpRs84v9/PZpIhTwsxwC90aWbO9huHrx7R/68wWPpPArIwb2WhsQ84JLGO0/yzbzTHac7HUwmPFkwjT246bK85tjrPGOTGL1Z44i8yuaGveOkWr0h+EI8Po0XPGnkD73Kr0m8pUWZvEWPwrwIn4K9qWGbPewH5jsZRms7GuvFPCTzKz2eLcq8+2sVvAc82rwOwyo9gfsdPcrocb2o0QC9FLF5vCRD/7uLlAK9RAxlvO+eH71qJkI8Cb+3vOY7FL39PsY7u9nJOvhFpb29fqQ7czF3vSwrML3ddWC8Pei8vMXvUL1LArc8j4QZvJBu9btzzcc8rvj3vBSlIL14/ME6yEIQPfOONj395m89tZ/9u8E1k7wUx508PAq6PKh5Kr1P5/u8DxuBO+NUhzyt7J48heBivcrRxjyzX5M8j+hIPU1Nczw1Qbc8KjlRPIMmJbwCOGc9HZmqvZHxUj0M6Ha8DCxxvYDc7zyhMwW9Po0XPIuUgrwegLe7Z/IwvMlOaTr8Kmo9zy2QutWVsjtywnU72lj6O0sCN73xeto8lEfhPCsAqbyWbxk9GutFPProtzzVlbK86U0ovb5R1TvgGHO9DCxxPFPfFT3DrZ486Ax9PYRyxT2j74o7wIVmvF2xojzRsfQ8JqRfPB4zM71StA48PdGRu+l7fj2sXm+8NTblPMnzQ7tu/608uFg0PQqS6DxdyE07TL68u5wkQL3miJi8SOXQPCW6Azsmdgm8tmbVPHXqrTzoOcy8ZW/TPBh+DD3cMy69wROWu2RxGz0uP4y7oKXVPHj8wbphuGQ93u3rOWMCGju+34Q8QcGou2EQOz2Y3NK87i+evFImXz1sh6K5ScCEPRpgIj6BgUq9fb6Cu3ams7zyuwU9Hq2Gu/r/4rxL64u8YEBZvKFVAj1Xu9C8bQoAPcjIPL2qJw89ySCTPAaXf7uazjG9hXFhvF8e3LzvDaG8fcrbPAEBhzoKqAy9iI7HvKTWFz2VkRa9fdUtvG/SXjuvyFk9AS/dPA2NUTyKHX68PRUMvAVqjb37xjq9D+6xuy/l7TwQwWI7tXEnvIYWvDwmpF+8bUMoPBoYFbygAPu8Iu3wvCToWb21UI49Xh/APWiutjww4h49ldUQvFCMVj2IsMS8hkMLPFqrZzz37U68Vt3NPJQwNrtbiWq9mMWnO/JBMjxASZ07lm+ZvMCbCjzW4ja9Po0XvcXKhLzTVs88nVqZOsWh6L2gjqq8V6QlPBFmvbsaAnE8VHCUO08Jebp6f5882b5xPZVbPb2Lqy29ygcgPZjnpDyrrTu9tPmbO4Vx4bt2prM8Ml35vFrN5DyIVoM9pJXsuzICVDyVA+e7hXHhOxCqN7yJM6K76er/OynYcL00p648kfFSPTPg1jzZmom953J0vLrFbT3uf/G8S+uLPAEN4DyRE1C8Po0XvMq6Gz31Xhi8zy2Qu8uNzLzIQhC9M1qqPcdkjTwv+xE9lNhfPcnzw7w3gJo8ms4xPRkNwzyzMsQ8mOekvOEKUryOcD29Rx75vMEqQTyq2go9V/EpPQc9vr2hMwW9XchNu4fFhD1vu7M85NozPS3yBz39Pka9GtQavLpKEzygpdU6X/CFPKPCuzyQbvW7AFwsu4S1Wz2oNbC88xRjPIVxYTti7j29vSZOvS/OQjw8Q2I8c7W4PfUdbT1odY68l00cPNQ9XL3zNmC9NGO0vLHRYz1KJDS92b7xPLQn8rxP8s28oiizvJyUpb15SUa9gK4ZPWMwcL0mjTQ8teP3vIoG0ztEDOW7ydyYPF3IzbxFj8K8XIYbPYlKzbxS4uQ8Y0YUPMReUrsP7jE8bIeiPFrvYby6lxc9VRb2ux3xgDzHkuM8hLVbPAxjrr17R368l0JKPZQZC700et88OdaoPAqoDD2NIzm9oj/ePJ96Tr2Xe3K8CnBrPKLkuDx3ug+9PvwYPYe7ljvWXIo8SBsqPY72aTuTf4K8gMXEvF3Izbzl7g+92ZCbPNZcCr3DiyG8DxsBPJsmCD1KO988WDPcOUjlULyquI28MIpIPCLtcL10XP68mxDkPOb6aLxRatm8ms4xvV9LqzwEH3Q8flgLvZ1amTy4AF48Kaqau2lTkbyxo408ZOCcPLArAr2K7ye9s1RBvOb66Lzja7I9AHNXPNTwV7zdXrU8djcyvQ7aVb3Y4O47KlvOPC/l7bzEl/o81w0+PJpIhb07h1y8Bq0jvdoqpDsDVxW9QvcBPVbSe7xXd1a8WAWGPADAWz14/ME5cgZwvGlqvDsyLyM8XfUcPL5RVb260D89Qe/+O6DSpDx7Gai7xGkkvcEqwbx6oZy8c7acvIiOxzuIpXK8Mi8jPWApLjws3qs8o+8KO/K7BT2Vv+w8ozwPPRILmLn5Q908zePaOp1amTxIdk+9A6foO5rZAz37rw+9g1R7vCzHALxUnuq7KlB8vJJ0sLyrdBO7Htvcu/rot7zPszw9/EmYvCUHCL0pwUW8pvZMPEUJFj1Ralm80nhMPAJlNj15a0M9oWytPEAczjxQuaW83u1ru4fSQby0+Zs8+UNdPSjjwrw6+KW8TL68uc6qMr1dI3M7YYqOvKg1ML0cevw8Fa4qvQYzUD3a6Xg9ISSuPeHzpj0YXA+8nmbyPH/+7Dy75Js8JwVAOwEjhDwluoO7yW0XPVekJTwkm1W9V2CrPOLRqTyaaoI7FriYPftrFbrn9xm942uyPJsEi7x6dE08'

#### Search by text embedding with `tools.embed_text` with an in-corpus embedding

In [8]:
result = impresso.search.find(
  country="FR",
  embedding=first_item_embeddings,
  limit=2
)

result

### Other tools

#### Convert embedding to an array of floats and back

In [9]:
original_embedding = impresso.content_items.get_embeddings("EXP-1951-11-23-a-i0001")[0]
original_embedding

'gte-768:pRhKvXXfWz0f+gq9dFx+PZVbvb04PCC9mMWnOj6kQrwie6A8JTVevWjFYbxStA48ECQLvZTBtD2Qece8ramIPSPfTz2Pm8Q6GAS5PTq0q7umh0s9hTmdPRPpmjyLlAK8mz0zvJFJKb2Ra6Y9drPwvdbBnb1stXg9cP1lvVgzXLuFOLk8YzDwPN7XpD3gqXG8XJJ0PeEK0jwSC5g6TGOXPIP51TuAIGq8HGPRu3p0TTxk1co8fjaOu6fJfbyBgUq8LW1iPARMQ7uD+dW7ExdxPbT5m7rYnHQ8jwpGPSW6Azzpnfu9tqpPPRh9KD6/fFy9hIeFvHqhHLtONsi8igZTO1X/SrxB+lC9EF0zPebY67y75Js9468sPd4au7yx8+A8DxuBO67497zAeQ29XzQAPeOCXbyrxOY8LpnNPaY6RzyNe4+924uEPG7/Lb2UR+E8BzxaPK0a9byFcWG7aJeLOycyDzzN+Jo9/9hOPc5xCj197Ng7Ky5/vR7Pgzz+zfw8CH0FvSpwjr337U48AEUBvbiOjbpHS0g9q5YQPa0a9TyA3O+8mnbbvK6/z7yX3ho93JfdvPlZgbxTRKm9nEY9vSUeM73ucxi9JqTfvMuk9zwteDQ93tbAvG+kiLsPfzA97Admu5pqgrxKDQm9zdeBvK1Rsr2nslK8ySCTu6jHkr0JnTo9fxSRPMdFXz04avY8+XqaPUv35Lzcl908KZR2vfJBMr10tFQ9O1kGO+nTVLz0Sjy9ZXqlu/3PRL3i0am8OsvWvN4DED1dyM28VegfvGBAWT1Mvrw7KcFFvDW7Cj2/hy49j5tEvHz3qjxJc4C8xcoEvT9V9jzmzBI6H9gNvTFznT0kFSk7a/eHPVVDRTvGvzI98kEyPMCbCjxOHx08T+d7PWASg7zHtOC8DwVdPNpBzzyYxSe5ml+wvGWoezmwN1s8Twn5PIQ6Ab1ASR06PL01PbHFCr0MsLK9x3u4vDMhgj0SIsO8qs84PKQaEr3Pvg49s1+TPMqYnrxOS4i9C7uEveNUhzt0Lqi8rJ+avS/lbTu7jEU953J0u3knST2FceE6erjHPJppnj1awQs9k8wGvcPPm7y0+Rs7x501vV6EU7x139u72DhFPZXVELwCChE9+vOJu32+AjzJ80O7Y3RqPL72r7yk7UI9Ir8avS14tLzjdgS9U8DnvBgmNr3uc5g8jeoQPfoh4LuD+VU87lEbOwBcrDve1kA8xgMtuzHAIT01CA+9luHpPG/SXjrpvCm8tAX1PItyhTx8n1Q9zy0QuqszaL0ZL0A8ni3Ku+s/B729zIy9Wn2RvDq0qzuvZKo7s41pvTfQ7bwd8QA9PSy3O316iD1jwW49vaz6u83XgTzRpRs84v9/PZpIhTwsxwC90aWbO9huHrx7R/68wWPpPArIwb2WhsQ84JLGO0/yzbzTHac7HUwmPFkwjT246bK85tjrPGOTGL1Z44i8yuaGveOkWr0h+EI8Po0XPGnkD73Kr0m8pUWZvEWPwrwIn4K9qWGbPewH5jsZRms7GuvFPCTzKz2eLcq8+2sVvAc82rwOwyo9gfsdPcrocb2o0QC9FLF5vCRD/7uLlAK9RAxlvO+eH71qJkI8Cb+3vOY7FL39PsY7u9nJOvhFpb29fqQ7czF3vSwrML3ddWC8Pei8vMXvUL1LArc8j4QZvJBu9btzzcc8rvj3vBSlIL14/ME6yEIQPfOONj395m89tZ/9u8E1k7wUx508PAq6PKh5Kr1P5/u8DxuBO+NUhzyt7J48heBivcrRxjyzX5M8j+hIPU1Nczw1Qbc8KjlRPIMmJbwCOGc9HZmqvZHxUj0M6Ha8DCxxvYDc7zyhMwW9Po0XPIuUgrwegLe7Z/IwvMlOaTr8Kmo9zy2QutWVsjtywnU72lj6O0sCN73xeto8lEfhPCsAqbyWbxk9GutFPProtzzVlbK86U0ovb5R1TvgGHO9DCxxPFPfFT3DrZ486Ax9PYRyxT2j74o7wIVmvF2xojzRsfQ8JqRfPB4zM71StA48PdGRu+l7fj2sXm+8NTblPMnzQ7tu/608uFg0PQqS6DxdyE07TL68u5wkQL3miJi8SOXQPCW6Azsmdgm8tmbVPHXqrTzoOcy8ZW/TPBh+DD3cMy69wROWu2RxGz0uP4y7oKXVPHj8wbphuGQ93u3rOWMCGju+34Q8QcGou2EQOz2Y3NK87i+evFImXz1sh6K5ScCEPRpgIj6BgUq9fb6Cu3ams7zyuwU9Hq2Gu/r/4rxL64u8YEBZvKFVAj1Xu9C8bQoAPcjIPL2qJw89ySCTPAaXf7uazjG9hXFhvF8e3LzvDaG8fcrbPAEBhzoKqAy9iI7HvKTWFz2VkRa9fdUtvG/SXjuvyFk9AS/dPA2NUTyKHX68PRUMvAVqjb37xjq9D+6xuy/l7TwQwWI7tXEnvIYWvDwmpF+8bUMoPBoYFbygAPu8Iu3wvCToWb21UI49Xh/APWiutjww4h49ldUQvFCMVj2IsMS8hkMLPFqrZzz37U68Vt3NPJQwNrtbiWq9mMWnO/JBMjxASZ07lm+ZvMCbCjzW4ja9Po0XvcXKhLzTVs88nVqZOsWh6L2gjqq8V6QlPBFmvbsaAnE8VHCUO08Jebp6f5882b5xPZVbPb2Lqy29ygcgPZjnpDyrrTu9tPmbO4Vx4bt2prM8Ml35vFrN5DyIVoM9pJXsuzICVDyVA+e7hXHhOxCqN7yJM6K76er/OynYcL00p648kfFSPTPg1jzZmom953J0vLrFbT3uf/G8S+uLPAEN4DyRE1C8Po0XvMq6Gz31Xhi8zy2Qu8uNzLzIQhC9M1qqPcdkjTwv+xE9lNhfPcnzw7w3gJo8ms4xPRkNwzyzMsQ8mOekvOEKUryOcD29Rx75vMEqQTyq2go9V/EpPQc9vr2hMwW9XchNu4fFhD1vu7M85NozPS3yBz39Pka9GtQavLpKEzygpdU6X/CFPKPCuzyQbvW7AFwsu4S1Wz2oNbC88xRjPIVxYTti7j29vSZOvS/OQjw8Q2I8c7W4PfUdbT1odY68l00cPNQ9XL3zNmC9NGO0vLHRYz1KJDS92b7xPLQn8rxP8s28oiizvJyUpb15SUa9gK4ZPWMwcL0mjTQ8teP3vIoG0ztEDOW7ydyYPF3IzbxFj8K8XIYbPYlKzbxS4uQ8Y0YUPMReUrsP7jE8bIeiPFrvYby6lxc9VRb2ux3xgDzHkuM8hLVbPAxjrr17R368l0JKPZQZC700et88OdaoPAqoDD2NIzm9oj/ePJ96Tr2Xe3K8CnBrPKLkuDx3ug+9PvwYPYe7ljvWXIo8SBsqPY72aTuTf4K8gMXEvF3Izbzl7g+92ZCbPNZcCr3DiyG8DxsBPJsmCD1KO988WDPcOUjlULyquI28MIpIPCLtcL10XP68mxDkPOb6aLxRatm8ms4xvV9LqzwEH3Q8flgLvZ1amTy4AF48Kaqau2lTkbyxo408ZOCcPLArAr2K7ye9s1RBvOb66Lzja7I9AHNXPNTwV7zdXrU8djcyvQ7aVb3Y4O47KlvOPC/l7bzEl/o81w0+PJpIhb07h1y8Bq0jvdoqpDsDVxW9QvcBPVbSe7xXd1a8WAWGPADAWz14/ME5cgZwvGlqvDsyLyM8XfUcPL5RVb260D89Qe/+O6DSpDx7Gai7xGkkvcEqwbx6oZy8c7acvIiOxzuIpXK8Mi8jPWApLjws3qs8o+8KO/K7BT2Vv+w8ozwPPRILmLn5Q908zePaOp1amTxIdk+9A6foO5rZAz37rw+9g1R7vCzHALxUnuq7KlB8vJJ0sLyrdBO7Htvcu/rot7zPszw9/EmYvCUHCL0pwUW8pvZMPEUJFj1Ralm80nhMPAJlNj15a0M9oWytPEAczjxQuaW83u1ru4fSQby0+Zs8+UNdPSjjwrw6+KW8TL68uc6qMr1dI3M7YYqOvKg1ML0cevw8Fa4qvQYzUD3a6Xg9ISSuPeHzpj0YXA+8nmbyPH/+7Dy75Js8JwVAOwEjhDwluoO7yW0XPVekJTwkm1W9V2CrPOLRqTyaaoI7FriYPftrFbrn9xm942uyPJsEi7x6dE08'

In [10]:
from impresso.util.embeddings import embedding_to_vector, vector_to_embedding

array = embedding_to_vector(original_embedding)
array[:10]  # show first 10 values

[-0.049339909106492996,
 0.053679902106523514,
 -0.033929940313100815,
 0.062099888920784,
 -0.09245983511209488,
 -0.03911992907524109,
 0.0012799976393580437,
 -0.011879978701472282,
 0.019589964300394058,
 -0.054249901324510574]

In [11]:
recreated_embedding = vector_to_embedding(array, 'gte-768')
recreated_embedding

'gte-768:pRhKvXXfWz0f+gq9dFx+PZVbvb04PCC9mMWnOj6kQrwie6A8JTVevWjFYbxStA48ECQLvZTBtD2Qece8ramIPSPfTz2Pm8Q6GAS5PTq0q7umh0s9hTmdPRPpmjyLlAK8mz0zvJFJKb2Ra6Y9drPwvdbBnb1stXg9cP1lvVgzXLuFOLk8YzDwPN7XpD3gqXG8XJJ0PeEK0jwSC5g6TGOXPIP51TuAIGq8HGPRu3p0TTxk1co8fjaOu6fJfbyBgUq8LW1iPARMQ7uD+dW7ExdxPbT5m7rYnHQ8jwpGPSW6Azzpnfu9tqpPPRh9KD6/fFy9hIeFvHqhHLtONsi8igZTO1X/SrxB+lC9EF0zPebY67y75Js9468sPd4au7yx8+A8DxuBO67497zAeQ29XzQAPeOCXbyrxOY8LpnNPaY6RzyNe4+924uEPG7/Lb2UR+E8BzxaPK0a9byFcWG7aJeLOycyDzzN+Jo9/9hOPc5xCj197Ng7Ky5/vR7Pgzz+zfw8CH0FvSpwjr337U48AEUBvbiOjbpHS0g9q5YQPa0a9TyA3O+8mnbbvK6/z7yX3ho93JfdvPlZgbxTRKm9nEY9vSUeM73ucxi9JqTfvMuk9zwteDQ93tbAvG+kiLsPfzA97Admu5pqgrxKDQm9zdeBvK1Rsr2nslK8ySCTu6jHkr0JnTo9fxSRPMdFXz04avY8+XqaPUv35Lzcl908KZR2vfJBMr10tFQ9O1kGO+nTVLz0Sjy9ZXqlu/3PRL3i0am8OsvWvN4DED1dyM28VegfvGBAWT1Mvrw7KcFFvDW7Cj2/hy49j5tEvHz3qjxJc4C8xcoEvT9V9jzmzBI6H9gNvTFznT0kFSk7a/eHPVVDRTvGvzI98kEyPMCbCjxOHx08T+d7PWASg7zHtOC8DwVdPNpBzzyYxSe5ml+wvGWoezmwN1s8Twn5PIQ6Ab1ASR06PL01PbHFCr0MsLK9x3u4vDMhgj0SIsO8qs84PKQaEr3Pvg49s1+TPMqYnrxOS4i9C7uEveNUhzt0Lqi8rJ+avS/lbTu7jEU953J0u3knST2FceE6erjHPJppnj1awQs9k8wGvcPPm7y0+Rs7x501vV6EU7x139u72DhFPZXVELwCChE9+vOJu32+AjzJ80O7Y3RqPL72r7yk7UI9Ir8avS14tLzjdgS9U8DnvBgmNr3uc5g8jeoQPfoh4LuD+VU87lEbOwBcrDve1kA8xgMtuzHAIT01CA+9luHpPG/SXjrpvCm8tAX1PItyhTx8n1Q9zy0QuqszaL0ZL0A8ni3Ku+s/B729zIy9Wn2RvDq0qzuvZKo7s41pvTfQ7bwd8QA9PSy3O316iD1jwW49vaz6u83XgTzRpRs84v9/PZpIhTwsxwC90aWbO9huHrx7R/68wWPpPArIwb2WhsQ84JLGO0/yzbzTHac7HUwmPFkwjT246bK85tjrPGOTGL1Z44i8yuaGveOkWr0h+EI8Po0XPGnkD73Kr0m8pUWZvEWPwrwIn4K9qWGbPewH5jsZRms7GuvFPCTzKz2eLcq8+2sVvAc82rwOwyo9gfsdPcrocb2o0QC9FLF5vCRD/7uLlAK9RAxlvO+eH71qJkI8Cb+3vOY7FL39PsY7u9nJOvhFpb29fqQ7czF3vSwrML3ddWC8Pei8vMXvUL1LArc8j4QZvJBu9btzzcc8rvj3vBSlIL14/ME6yEIQPfOONj395m89tZ/9u8E1k7wUx508PAq6PKh5Kr1P5/u8DxuBO+NUhzyt7J48heBivcrRxjyzX5M8j+hIPU1Nczw1Qbc8KjlRPIMmJbwCOGc9HZmqvZHxUj0M6Ha8DCxxvYDc7zyhMwW9Po0XPIuUgrwegLe7Z/IwvMlOaTr8Kmo9zy2QutWVsjtywnU72lj6O0sCN73xeto8lEfhPCsAqbyWbxk9GutFPProtzzVlbK86U0ovb5R1TvgGHO9DCxxPFPfFT3DrZ486Ax9PYRyxT2j74o7wIVmvF2xojzRsfQ8JqRfPB4zM71StA48PdGRu+l7fj2sXm+8NTblPMnzQ7tu/608uFg0PQqS6DxdyE07TL68u5wkQL3miJi8SOXQPCW6Azsmdgm8tmbVPHXqrTzoOcy8ZW/TPBh+DD3cMy69wROWu2RxGz0uP4y7oKXVPHj8wbphuGQ93u3rOWMCGju+34Q8QcGou2EQOz2Y3NK87i+evFImXz1sh6K5ScCEPRpgIj6BgUq9fb6Cu3ams7zyuwU9Hq2Gu/r/4rxL64u8YEBZvKFVAj1Xu9C8bQoAPcjIPL2qJw89ySCTPAaXf7uazjG9hXFhvF8e3LzvDaG8fcrbPAEBhzoKqAy9iI7HvKTWFz2VkRa9fdUtvG/SXjuvyFk9AS/dPA2NUTyKHX68PRUMvAVqjb37xjq9D+6xuy/l7TwQwWI7tXEnvIYWvDwmpF+8bUMoPBoYFbygAPu8Iu3wvCToWb21UI49Xh/APWiutjww4h49ldUQvFCMVj2IsMS8hkMLPFqrZzz37U68Vt3NPJQwNrtbiWq9mMWnO/JBMjxASZ07lm+ZvMCbCjzW4ja9Po0XvcXKhLzTVs88nVqZOsWh6L2gjqq8V6QlPBFmvbsaAnE8VHCUO08Jebp6f5882b5xPZVbPb2Lqy29ygcgPZjnpDyrrTu9tPmbO4Vx4bt2prM8Ml35vFrN5DyIVoM9pJXsuzICVDyVA+e7hXHhOxCqN7yJM6K76er/OynYcL00p648kfFSPTPg1jzZmom953J0vLrFbT3uf/G8S+uLPAEN4DyRE1C8Po0XvMq6Gz31Xhi8zy2Qu8uNzLzIQhC9M1qqPcdkjTwv+xE9lNhfPcnzw7w3gJo8ms4xPRkNwzyzMsQ8mOekvOEKUryOcD29Rx75vMEqQTyq2go9V/EpPQc9vr2hMwW9XchNu4fFhD1vu7M85NozPS3yBz39Pka9GtQavLpKEzygpdU6X/CFPKPCuzyQbvW7AFwsu4S1Wz2oNbC88xRjPIVxYTti7j29vSZOvS/OQjw8Q2I8c7W4PfUdbT1odY68l00cPNQ9XL3zNmC9NGO0vLHRYz1KJDS92b7xPLQn8rxP8s28oiizvJyUpb15SUa9gK4ZPWMwcL0mjTQ8teP3vIoG0ztEDOW7ydyYPF3IzbxFj8K8XIYbPYlKzbxS4uQ8Y0YUPMReUrsP7jE8bIeiPFrvYby6lxc9VRb2ux3xgDzHkuM8hLVbPAxjrr17R368l0JKPZQZC700et88OdaoPAqoDD2NIzm9oj/ePJ96Tr2Xe3K8CnBrPKLkuDx3ug+9PvwYPYe7ljvWXIo8SBsqPY72aTuTf4K8gMXEvF3Izbzl7g+92ZCbPNZcCr3DiyG8DxsBPJsmCD1KO988WDPcOUjlULyquI28MIpIPCLtcL10XP68mxDkPOb6aLxRatm8ms4xvV9LqzwEH3Q8flgLvZ1amTy4AF48Kaqau2lTkbyxo408ZOCcPLArAr2K7ye9s1RBvOb66Lzja7I9AHNXPNTwV7zdXrU8djcyvQ7aVb3Y4O47KlvOPC/l7bzEl/o81w0+PJpIhb07h1y8Bq0jvdoqpDsDVxW9QvcBPVbSe7xXd1a8WAWGPADAWz14/ME5cgZwvGlqvDsyLyM8XfUcPL5RVb260D89Qe/+O6DSpDx7Gai7xGkkvcEqwbx6oZy8c7acvIiOxzuIpXK8Mi8jPWApLjws3qs8o+8KO/K7BT2Vv+w8ozwPPRILmLn5Q908zePaOp1amTxIdk+9A6foO5rZAz37rw+9g1R7vCzHALxUnuq7KlB8vJJ0sLyrdBO7Htvcu/rot7zPszw9/EmYvCUHCL0pwUW8pvZMPEUJFj1Ralm80nhMPAJlNj15a0M9oWytPEAczjxQuaW83u1ru4fSQby0+Zs8+UNdPSjjwrw6+KW8TL68uc6qMr1dI3M7YYqOvKg1ML0cevw8Fa4qvQYzUD3a6Xg9ISSuPeHzpj0YXA+8nmbyPH/+7Dy75Js8JwVAOwEjhDwluoO7yW0XPVekJTwkm1W9V2CrPOLRqTyaaoI7FriYPftrFbrn9xm942uyPJsEi7x6dE08'

In [12]:
f"Original and recreated embeddings are the same: {original_embedding == recreated_embedding}"

'Original and recreated embeddings are the same: True'

### Embed an image

In [13]:
impresso.tools.embed_image("https://impresso-project.ch/assets/images/posts/rep-thomas.png", target="multimodal")

'openclip-768:7KKPPrpmmT7uiZ0/PjeWPlP4lb5np0w/6IqevVDlvz6K3TW9crhBv6GSO7/3ADE+mIP3Pr4ugb5G6cU+gDAwv7jOLD85dc4+ZuPyPv7WhD5u6UW+sNy4PSOtcD99sP8+qMarvZF2zL7+opW+jgGaPmeXBT/+NxG/Qt8LP+Ojhr/0/UK/8CfjPgGtPj+qnfm+GCGPvo2SL79Yl569MuE1P8Ymojxma9W+ad6/v4CMAD6LYRu/TxHDPUQOFL/vSHW/4FjfPrhmMj9MQOu+VOvivlYScb8L120/+cIxPvULvL5xtu49ITqJPHKkFT+yLCW/rK5ivzjBhr4U2X++kD6NPonkhr7QXiQ/1GYavSyamD4IGQG/raOxPqQZCz/QJVa/imMoP8KVrb5oMLe9kssZP+7RuD/HNGK/QRvYvUCeib5g6vo96lXsPSkHJT+uZ6w/Co+fPvLyL7+hEJK+Dv3tvistxb4wGto+AmIfPg8g7TwlsL4+1ku2P8g+xT4TF8k+gABAvsHUlj5w+Vg/SsTvviVB1b46nkw/OuoAP/t3Bz/GdBG/evGrPxwgsL6Wjve+chrhPamvr7/mMHe/pqrzvtJXtz5B6CW/0Cf8vY/Kgb5/ewu/4o75van2UT7uU7K+KCIdPmk4yz8KQXs/xKeUP4LWDT6um2G/ftTjvZDhCD+jZuk+PFh0Pv5kabxWHSC+lgifP66jgz4QQDc+5K2dvR9jlT84JMM+XZK2vyD6Ib3LteG+WIMzvQrmjL/zGjG/SiofvvHgdD7e5am+OpGsPt6hl742J9M+TKZOQF9DGb4jUxk/6EIuv5Zm4r5+VVK/NJc6vpnzzb5kPo09yBaGPciqLr8YhCu9Vx4nP4jVgD9PiU+/mMFVPqK5o77OckS+P+QNPWm+Yr+B4uC+V5PUvT5wE79vMDa/AGfDvUSAP78qDGW+Fc34PcKKCr9OhTA+dAJjv6aEGr/uRJW+MSsYvzycjz7eo2Y93JN+vUHgH78dpKa+phLAvaTtNr/cQ9Y++Pcdv2fJXj3rMsO+D6u8vsQODL+U5II/4uoPP4ZWLr6OWe4/a8e1P7fSOT2GYQM+yjKCPtI00L17i6e+Es8Kv7qlAr9CbuQ+PkWAvnfpFz/H8Vc+ZIdlvsw/tL1meTo+3OIPv/1byz48ywa/VMsAPfDNPL5WYeS91KvmvRTnd77mOaq++iNhPnVZCD/oKKs+rzP3viKxDz957Du/NhunP9ppob6uSza/hBKIPxGqhD9sl7o9SIuAvnqwML6Cob89dbtMvwxyfT2eSmc/ueLCP5bHoL/5a8m+KMHBPaFunb7YxUE9n5WeP1O7Ab+Anl4/umIZvgCgHT8v/j2/x+4iv5DKaT9W4gO/h0phv/7wgT0II4u+IEEHvxSokb8MOLm9pDMLPjzzFD+8g669cNeEPAr1DD/WHKW+jKVEPHvRZj4ZVmi/aB+FP0l55b43fMy+pIhhPuzBcr8BdjY/fAwOvpoEzL9QBiW/VCNuPY/BCL8nUBm+iIsMviR9hb7YMd69xyLLPgpEh77uSpi++ocFP0JOND9Ho1E/gpefvVIVjr7Bj8g89YUQP/A5n77Y74+/dslSvuPVAr8g01u/FBiMPmAzrb9kLTu+FOoEv7EYKz/eeQBAkLwLvh+kYz3dtX8+Lp64P0+5gT8ZrAE/VmFCv9I2lr6s0Iq9zkmAv20LCr4ECNs+BCbDvpyQhz4sB72/pkkAv7MpCz769Q2/OFgrPfY9xr6EdoA/OICMvuzx8r2jTC0/7lqAP1NzcD8YSEi/Mg4WvtUE/r4CE0A+El5jvln+cT/esEi/EG7Avv+zVD+4OeE+6sjHPo4HdT+/Br0+aiz6vkhqND55VGc/Fah9v/fHPL9CHlk+UzXWPrRdXL6jHNC7ys9Vvga8H75m8KQ90I89vfs9q7+k5b6+pa1tPiBfh77J3mk9O46jvYJYlD/aE868cZ0CPcg4Hj+Qd/8+1cGjPjXNir6LSLQ/+JP5v1DfJL7ykOW+ztqgv6h8db/LDm8/7kCbPRr5Q79FYwa/Zlq4PrfpIL+wU69AWpKWP9h3jb5bROO+hhKDPirMbz8f9xU/w+i3vskmkD7Yqji/lKcVv6JRcL5qBKA+on+9vh5/Cb9EKEM+9CWTPeCIxz26S9M+5vkXP+JxFT/3vL2+Wa0tP34a1ruGgrW+ULqKv39OC7/rLkA/cuYVPikher+5xRm77XitP96Rwr6gT2W/begCv01moj52eJq+PC0JP9rLnz4DMpy+owYhv5heKD8K1B8/MHacvsEAhL14gom+1+I1P7LeL7+8XAe/Llyovt2rf7wncYE/1huTP9ykIr5Wxc0+tMADP+L2YL/kiGg+yZjvPZpQ4j72EO6+b7onu67Yuj4+gaC+rUb7PEiC4792xle9wwZwvM8A2T89Eoy/SK7XPigMEL+w2j0/ldJEP4yVkz7r4X6+9Ekqv/3sM7/GpJ4+cODVvaYetb0DQrM+9NIlP3j9yD5FqzG/mo0LvVoujb66Vg8/+PSIv5DpIz8MbWS+tIG5vmBB97/22Jo/oyKcPiQftj5Ovgc/m6RmPjN+er8/b2g+QPmbPtpyq76aEhk/ol02v2QiQrwtCnXAVqikO2ZNjz5ADzS/1N0UvyxA7D0ST/g+qw9Yv0mIn76thBq/hlo9vif7Bb+IQdm+78J5P2LnBb7rzgK/PmW/vrqSS76UO0y+gC0uP4OlKL0mtnE/QX1dPUYEPz6uPhG/ynlaPuhsKD805do+t9KBPijnGD9jFDW/sSQVPqA4LT/Is6q976uJPbz6LT9t+pO+nnZGv46Qer+zLAs/Tp8qv1yhKL+uV+w+0gYwPw66BT+Weli/borOvzSLVD+oTQw+EuDKPlF/pj5AJfE9nwv7PFD5AL8VY46+MkrHvuaawr7sMQm/+vfxP1PHfT1EEz8/nKgRP5Zrij5HPi+8QqibPbzD8b5+yya+Q/OFPU5yvD7xUms/IkSFPxzUmr4c2os/lyjzuwnKuL6Nuci9HsbYvpo8lz6mrou+3Y0VPsKgxr2YxCG/g83oPcCVQD7Qdqq9WC40P3tgoz8zypI+Xct9PNf3oD9me2o+N5CFPimx6b4l7dY/9e98vmzfC8A33CS/vPUsvwrGkz55N7e+rKfjPiv3vb6eN7k+qHDcPljz5L0M4Ke/r0BTPcWTZz8C5LY+RSvLP/dtcTxbObY/ckO6Pi9CbL7e9AE+nLMPvlPpJr280W6+9WZtP9LpGr/2AhY+cW6LvrBYGD8Eweu6dhyfvnsZDz5ew8M+Am8kP7NBJD5SkB2+sEGCvp1Dkb10+NG+7lPGvhTAnD/X5Jk/LwgtPsYJBj+2YxG/7Mmyu5uTyz4OjmY/rH7aPLY/oL6qtZq+iLrfP0e2kr/1R1C+OpzqvmX9ob4BcjS/2IcePtQPKDzwB1a/Y1EqP15LBjy4Lru+BHjRPvdM+r4xNe29XCJAP21NCD48E7w9MhrLvcQx3T53gSK+LuxIv4EONL+E/qg+C2XbPc/sgr6KrfO+m30tP+3QhT9z4SG/RP1OvjJPfr/5RIC+xw/TPE6MWj9mzo++RKsKvuv9FL432Re/GFCdvun3MD+uSBK/0cjiPiCV5T6+b0k/s/lLPUFiTb58xrQ+lwPGPqc4Bj+mZwE+FlApP5S7Kb/28jw+1F+Hvoygrz6f11i+/mf7P+DBC76D4Vc9rrEWP3J+lr5Bii2+LGBZP4oWSL/MyP2+0QkaP/2Djr6sdBK/18MwPxAObT4CkFw/AlKDP6h76r6Q+i8/6qifviQDND8YbgC/XRervzaG374z+hu/A2tFv4OgnD7fNnW++pVJP0gkij91npw/KdfSP6yDFb9Yyni+sca1vgYBaz7wZRq/d0k8v731CD8/tIS+q6M2PIzCGz7aMQO/P9+0PlcYWz44ulQ/3DxfvB7qBr+wTW8+W1VovgS4A7/CxYQ8xNGsvr6ozb4sXCe+mqe+PqVoHT/kLk0/CIQMPjcJKD68MDG/n9FhPgBmv74CKlM/YKxgP4u/Pb70ImA/tPqxPuT7wr6TkZE/rcsnvxDx1b+M5gw/VjvNv3xJSr/ByYO/'